# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wateralg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_watershed(object):
    def setupUi(self, watershed):
        watershed.setObjectName("watershed")
        watershed.resize(979, 891)
        watershed.setStyleSheet("\n"
"background-image: url(:/newPrefix/timg (6).jpg);")
        self.pushButton = QtWidgets.QPushButton(watershed)
        self.pushButton.setGeometry(QtCore.QRect(670, 180, 101, 51))
        self.pushButton.setStyleSheet("\n"
"font: 12pt \"微软雅黑\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(watershed)
        self.label.setGeometry(QtCore.QRect(40, 100, 481, 341))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(watershed)
        self.label_2.setGeometry(QtCore.QRect(0, -10, 371, 61))
        self.label_2.setStyleSheet("font: 24pt \"华文彩云\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(watershed)
        self.label_3.setGeometry(QtCore.QRect(40, 510, 481, 351))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(watershed)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.label_4.setStyleSheet("font: 14pt \"黑体\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(watershed)
        self.label_5.setGeometry(QtCore.QRect(10, 460, 81, 21))
        self.label_5.setStyleSheet("font: 14pt \"黑体\";")
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(watershed)
        self.textEdit.setGeometry(QtCore.QRect(580, 250, 311, 41))
        self.textEdit.setStyleSheet("border-image: url(:/newPrefix/7acb0a46f21fbe0992a4bab36b600c338644ad9b.jpg);")
        self.textEdit.setObjectName("textEdit")
        self.groupBox = QtWidgets.QGroupBox(watershed)
        self.groupBox.setGeometry(QtCore.QRect(560, 490, 321, 191))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 20, 91, 31))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 90, 91, 31))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(0, 60, 161, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(170, 60, 61, 21))
        self.lineEdit.setStyleSheet("border-image: url(:/newPrefix/7acb0a46f21fbe0992a4bab36b600c338644ad9b.jpg);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 60, 61, 21))
        self.lineEdit_2.setStyleSheet("border-image: url(:/newPrefix/7acb0a46f21fbe0992a4bab36b600c338644ad9b.jpg);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 140, 91, 31))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 140, 91, 31))
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_2 = QtWidgets.QGroupBox(watershed)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 690, 321, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 30, 91, 31))
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 90, 91, 31))
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 150, 91, 31))
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_9.setGeometry(QtCore.QRect(150, 150, 91, 31))
        self.pushButton_9.setStyleSheet("")
        self.pushButton_9.setObjectName("pushButton_9")

        self.retranslateUi(watershed)
        self.pushButton.clicked.connect(watershed.open_image)
        self.pushButton_2.clicked.connect(watershed.img_gray)
        self.pushButton_3.clicked.connect(watershed.find_marker)
        self.pushButton_4.clicked.connect(watershed.shed)
        self.pushButton_5.clicked.connect(watershed.save)
        self.pushButton_6.clicked.connect(watershed.binary)
        self.pushButton_7.clicked.connect(watershed.find_marker2)
        self.pushButton_8.clicked.connect(watershed.shed2)
        self.pushButton_9.clicked.connect(watershed.save2)
        QtCore.QMetaObject.connectSlotsByName(watershed)

    def retranslateUi(self, watershed):
        _translate = QtCore.QCoreApplication.translate
        watershed.setWindowTitle(_translate("watershed", "Form"))
        self.pushButton.setText(_translate("watershed", "打开原图"))
        self.label_2.setText(_translate("watershed", "图像分割——分水岭算法"))
        self.label_4.setText(_translate("watershed", "原图："))
        self.label_5.setText(_translate("watershed", "效果图："))
        self.groupBox.setTitle(_translate("watershed", "处理图像方式①"))
        self.pushButton_2.setText(_translate("watershed", "灰度图像"))
        self.pushButton_3.setText(_translate("watershed", "marker图像"))
        self.label_6.setText(_translate("watershed", "Canny算子低高阈值(非负整数)"))
        self.pushButton_4.setText(_translate("watershed", "最终效果图"))
        self.pushButton_5.setText(_translate("watershed", "保存图像"))
        self.groupBox_2.setTitle(_translate("watershed", "处理图像方式②"))
        self.pushButton_6.setText(_translate("watershed", "二值图像"))
        self.pushButton_7.setText(_translate("watershed", "marker图像"))
        self.pushButton_8.setText(_translate("watershed", "最终效果图"))
        self.pushButton_9.setText(_translate("watershed", "保存图像"))

